version: "3"

networks:
    web:
        external: true

services:
    platform:
        image: 0x12f/platform:dev
        environment:
            - DEBUG=1
            - ANALYTICS=0
            - SALT=si12Fd-d3stcR-hD19Ld
          # - DATABASE=mysql://user:secret@localhost/mydb
        volumes:
            - ./resource:/var/container/public/resource:ro
            - ./theme:/var/container/theme:ro
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.backend=site.0x12f.com
            - traefik.frontend.rule=Host:site.0x12f.com
            - traefik.frontend.redirect.entryPoint=https
            - traefik.docker.network=web
        networks:
            - web
