version: "3"

networks:
    web:
        external: true

services:
    platform:
        image: getwebspace/platform:dev
        environment:
            - DEBUG=1
            - SALT=si12Fd-d3stcR-hD19Ld
            - DATABASE=mysql://demo:D3hD4xg8hd@mysql/site
        volumes:
            - ./plugin:/var/container/plugin:ro
            - ./resource:/var/container/public/resource:ro
            - ./theme:/var/container/theme:ro
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.backend=getwebspace.org
            - traefik.frontend.rule=Host:getwebspace.org
            - traefik.frontend.redirect.entryPoint=https
            - traefik.docker.network=web
        networks:
            - web
        restart: always
